### ISSUE TITLE
During local development logo uploading is hard to test out of the box

### ISSUE THREAD

**Issue by addshore** [wbstack/api#37]

**Comment by jakobw** [comment]
Temporarily hacking https://github.com/wbstack/api/blob/3eb294d9e4100bd4ae35d16d8daaec268db03a93/app/Http/Controllers/WikiLogoController.php#L39 from `disk` to `persistentFake` worked!

Properly making this work in development likely involves changing `filesystems.php` to not use a gcs storage driver, but the local file system. https://laravel.com/docs/8.x/filesystem

Another difference is that the URL generated from the storage object e.g. in https://github.com/wbstack/api/blob/3eb294d9e4100bd4ae35d16d8daaec268db03a93/app/Http/Controllers/WikiLogoController.php#L79 is (obviously) absolute when hosted on GCS, but relative when using `persistentFake` and probably also when using the local fs.
